[build-system]
requires = ["setuptools>=61.0", "wheel", "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "rantanplan"
version = "2.0"
authors = [
  { name="Joan Espasa Arxer", email="foo@bar.com" },
]
description = "An automated planner based on planning modulo theories"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "unified-planning>=1.2.0",
    "protobuf",
    "z3-solver"
]

[project.scripts]
rantanplan = "rantanplan.cli:main"

[project.entry-points."unified_planning.engines"]
RantanPlan = "rantanplan.planner_wrapper:RantanPlanPlanner"

[project.urls]
"Homepage" = "https://github.com/pyPMT/rantanplan"
"Repository" = "https://github.com/pyPMT/rantanplan"

[tool.setuptools]
packages = ["rantanplan"]
include-package-data = true

[tool.setuptools.package-data]
rantanplan = ["bin/*", "cpp/**/*"]