(define (problem obj-gripper-x-1)
   (:domain obj-gripper-typed)
   (:objects rooma roomb - room
             ball4 ball3 ball2 ball1 - ball)
   (:init (= (robby-at) rooma)
          (= (holding left) no-ball)
          (= (holding right) no-ball)
          (= (ball-at ball4) rooma)
          (= (ball-at ball3) rooma)
          (= (ball-at ball2) rooma)
          (= (ball-at ball1) rooma))
   (:goal (and (= (ball-at ball4) roomb)
               (= (ball-at ball3) roomb)
               (= (ball-at ball2) roomb)
               (= (ball-at ball1) roomb))))
