;; Auto-generated by scripts/generate_refinery.py
;; Domain: pddl/bench/refinery/domain.pddl
;; Refineries: 3  Products: 2
;; Total capacity: 186  Total demand: 111  (slack: 40%)
;; max-active: 2  (concurrent operator slots)

(define (problem refinery-p01)
  (:domain refinery)
  (:objects
    r1 r2 r3 - refinery
    p1 p2 - product
  )
  (:init
    (= (output r1) 0)
    (= (capacity r1) 74)
    (= (calibration r1) 0)
    (= (output r2) 0)
    (= (capacity r2) 44)
    (= (calibration r2) 0)
    (= (output r3) 0)
    (= (capacity r3) 68)
    (= (calibration r3) 0)
    (= (combined-oil) 0)
    (= (demand p1) 54)
    (= (intermediate-amount p1) 0)
    (= (demand p2) 57)
    (= (intermediate-amount p2) 0)
    (= (active-count) 0)
    (= (max-active) 2)
  )
  (:goal (and (delivered p1)  (delivered p2)))
)
