#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iomanip>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include "unified_planning.pb.h" // Generated by protoc

#include "problem/problem.h"

#include "z3++.h"

// Function to print the complete planning problem structure using enhanced planning classes
PlanGenerationResult solve_planning_problem(const planmt::Problem& problem) {
    PlanGenerationResult result;
    auto* log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);

    std::cout << problem.to_string() << std::endl;
    
    result.set_status(PlanGenerationResult_Status_UNSOLVABLE_INCOMPLETELY);
    log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);
    log_message->set_message("C++ planner: Custom effects tested successfully.");

    return result;
}
int main(int argc, char* argv[]) {
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    if (argc != 3) {
        std::cerr << "Usage: " << argv[0] << " <input_problem.pb> <output_solution.pb>" << std::endl;
        return 1;
    }

    // Read the problem from the input file
    Problem problem_msg;
    std::fstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input || !problem_msg.ParseFromIstream(&input)) {
        std::cerr << "Error: Could not open or parse problem file: " << argv[1] << std::endl;
        return 1;
    }

    // Create a Problem wrapper from the protobuf message
    planmt::Problem planning_problem(problem_msg);

    // Solve the planning problem
    PlanGenerationResult result = solve_planning_problem(planning_problem);

    // Write the result to the output file
    std::fstream output(argv[2], std::ios::out | std::ios::trunc | std::ios::binary);
    if (!output || !result.SerializeToOstream(&output)) {
        std::cerr << "Error: Could not write result to file: " << argv[2] << std::endl;
        return 1;
    }

    std::cout << "C++ Planner: Successfully wrote result to: " << argv[2] << std::endl;
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}