#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iomanip>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include "unified_planning.pb.h" // Generated by protoc

#include "problem/problem.h"
#include "encoders/grounded_encoder.h" 
#include "planners/sequential.h"    

#include "z3++.h"

// Function to print the complete planning problem structure using enhanced planning classes
PlanGenerationResult solve_planning_problem(const planmt::Problem& problem) {
    PlanGenerationResult result;
    auto* log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);

    // Create Z3 context
    z3::context ctx;

    // Instantiate the encoder/planner combination
    planmt::GroundedEncoder encoder(problem, ctx);
    planmt::SequentialPlanner planner(problem, encoder, ctx);

    // Call planner.search() and get the result
    planmt::Plan plan = planner.search();
    
    if (!plan.is_empty()) {
        // Plan found - populate the result
        result.set_status(PlanGenerationResult_Status_SOLVED_SATISFICING);
        
        // Convert plan to protobuf and set it in the result
        *result.mutable_plan() = plan.to_protobuf();
        
        log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("Plan found with " + std::to_string(plan.length()) + " actions.");
    } else {
        // No plan found
        result.set_status(PlanGenerationResult_Status_UNSOLVABLE_INCOMPLETELY);
        log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("No plan found within the search limit.");
    }
    
    log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);
    log_message->set_message("Finished solving the problem.");

    return result;
}
int main(int argc, char* argv[]) {
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    if (argc != 3) {
        std::cerr << "Usage: " << argv[0] << " <input_problem.pb> <output_solution.pb>" << std::endl;
        return 1;
    }

    // Read the problem from the input file
    Problem problem_msg;
    std::fstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input || !problem_msg.ParseFromIstream(&input)) {
        std::cerr << "Error: Could not open or parse problem file: " << argv[1] << std::endl;
        return 1;
    }

    // Create a Problem wrapper from the protobuf message
    planmt::Problem planning_problem(problem_msg);
    //std::cout << planning_problem.to_string() << std::endl;

    // Solve the planning problem
    PlanGenerationResult result = solve_planning_problem(planning_problem);

    // Write the result to the output file
    std::fstream output(argv[2], std::ios::out | std::ios::trunc | std::ios::binary);
    if (!output || !result.SerializeToOstream(&output)) {
        std::cerr << "Error: Could not write result to file: " << argv[2] << std::endl;
        return 1;
    }

    std::cout << "C++ Planner: Successfully wrote result to: " << argv[2] << std::endl;
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}