#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iomanip>
#include <chrono>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include "unified_planning.pb.h" // Generated by protoc

#include "config/config.h"
#include "problem/problem.h"
#include "encoders/encoder_factory.h" 
#include "planners/sequential.h"
#include "planners/propagators/propagator_factory.h"
#include "util/memory_tracker.h"
#include "util/stats.h"
#include "symmetries/smt_symmetry_checker.h"
#include "arpg/arpg.h"
#include "abstraction/achievers_analysis.h"
#include "analysis/relaxed_planning_graph.h"

#include "z3++.h"

// Helper function to write result and exit
int write_result_and_exit(const PlanGenerationResult& result, const char* output_file) {
    std::fstream output(output_file, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!output || !result.SerializeToOstream(&output)) {
        std::cerr << "Error: Could not write result to file: " << output_file << std::endl;
        return 1;
    }
    if (planmt::Config::instance().is_info()) {
        std::cout << "C++ Planner: Successfully wrote result to: " << output_file << std::endl;
    }
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}

// Function to print the complete planning problem structure using enhanced planning classes
PlanGenerationResult solve_planning_problem(const planmt::Problem& problem) {
    auto& config = planmt::Config::instance();
    
    // Memory tracking is always enabled
    
    PlanGenerationResult result;
    auto* log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);

        // Create Z3 context
    z3::context ctx;

    // Instantiate the encoder/planner combination
    auto encoder = planmt::EncoderFactory::create_encoder(config.planner.encoder, problem, ctx);
    encoder->set_parallelism_strategy(config.planner.parallelism_strategy);
    if (config.is_info()) {
        std::cout << "Using encoder type: " << config.planner.encoder << std::endl;
        std::cout << "Using parallelism strategy: " << encoder->get_parallelism_strategy_name() << std::endl;
    }
    
    // Create planner and set propagator
    planmt::SequentialPlanner planner(problem, *encoder, ctx);
    planner.set_propagator_strategy(config.propagators.type);
    if (config.is_info()) {
        std::cout << "Using propagator strategy: " << planner.get_propagator_strategy_name() << std::endl;
    }

    // Call planner.search() and get the result
    planmt::Plan plan = planner.search();
    if (planner.solution_found()) {
        // Plan found (even if empty) - populate the result
        result.set_status(PlanGenerationResult_Status_SOLVED_SATISFICING);
        
        // Convert plan to protobuf and set it in the result
        *result.mutable_plan() = plan.to_protobuf();
        
        if (config.is_info()) {
            log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("Plan found with " + std::to_string(plan.length()) + " actions.");
        }
    } else {
        // No plan found
        result.set_status(PlanGenerationResult_Status_UNSOLVABLE_INCOMPLETELY);
        if (config.is_info()) {
            log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("No plan found within the search limit.");
        }
    }
    
    if (config.is_verbose()) {
        log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("Finished solving the problem.");
    }
    
    // Add memory tracking information to result
    double current_memory = planmt::MemoryTracker::instance().get_current_memory_mb();
    
    log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);
    log_message->set_message("Memory usage - Current: " + std::to_string(current_memory) + " MB");

    return result;
}
int main(int argc, char* argv[]) {
    GOOGLE_PROTOBUF_VERIFY_VERSION;
    
    try {
        // Initialize configuration first
        planmt::Config::instance().initialize(argc, argv);
        auto& config = planmt::Config::instance();
        
        if (argc < 3) {
            std::cerr << "Usage: " << argv[0] << " <input_problem.pb> <output_solution.pb> [OPTIONS]" << std::endl;
            std::cerr << "Use --help for detailed options" << std::endl;
            return 1;
        }
    } catch (const std::exception& e) {
        std::cerr << "Configuration error: " << e.what() << std::endl;
        return 1;
    }

    // Read the problem from the input file
    Problem problem_msg;
    std::fstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input || !problem_msg.ParseFromIstream(&input)) {
        std::cerr << "Error: Could not open or parse problem file: " << argv[1] << std::endl;
        return 1;
    }

    // Create a Problem wrapper from the protobuf message
    planmt::Problem planning_problem(problem_msg);
    //std::cout << planning_problem.to_string() << std::endl;

    // === RELAXED PLANNING GRAPH CHECK ===
    // Create and build the RPG to check for unsolvability
    planmt::RelaxedPlanningGraph rpg(planning_problem);
    bool goals_reachable = rpg.build();

    // If goals are not reachable in the relaxed planning graph, the problem is unsolvable
    if (!goals_reachable) {
        PlanGenerationResult result;
        result.set_status(PlanGenerationResult_Status_UNSOLVABLE_PROVEN);

        auto* log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("Problem proven unsolvable: goals not reachable in relaxed planning graph");

        return write_result_and_exit(result, argv[2]);
    }

    // Remove unreachable actions to reduce encoding size
    size_t total_actions = planning_problem.action_count();
    size_t removed_actions = 0;
    if (planmt::Config::instance().global.enable_action_removal) {
        removed_actions = rpg.remove_unreachable_actions();
        if (planmt::Config::instance().is_info()) {
            double percentage = (double)removed_actions / total_actions * 100.0;
            std::cout << "[RPG] Removed " << removed_actions << "/" << total_actions
                        << " unreachable actions (" << std::fixed << std::setprecision(1)
                        << percentage << "%)" << std::endl;
        }
    }

    // Extract lower bound from RPG for starting timestep
    int rpg_lower_bound = rpg.get_minimum_steps_lower_bound();

    // Check if symmetry detection is requested
    auto& config = planmt::Config::instance();

    // Set the starting timestep from RPG lower bound in config
    config.planner.start_timestep = rpg_lower_bound;

    // Solve the planning problem using configuration
    PlanGenerationResult result = solve_planning_problem(planning_problem);

    // Print statistics if in debug mode, and optionally write to file
    if (config.is_debug()) {
        planmt::Stats::instance().print_all();
    }
    
    // Write statistics to file if specified
    if (!config.global.stats_file.empty()) {
        planmt::Stats::instance().write_to_file(config.global.stats_file);
    }

    return write_result_and_exit(result, argv[2]);
}