#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iomanip>
#include <chrono>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include "unified_planning.pb.h" // Generated by protoc

#include "config/config.hpp"
#include "config/strategy_registry.hpp"
#include "problem/problem.hpp"
#include "planners/sequential.hpp"
#include "planners/formula_exporter.hpp"
#include "util/memory_tracker.hpp"
#include "util/stats.hpp"
#include "util/logger.hpp"
#include "symmetries/smt_symmetry_checker.hpp"
#include "arpg/arpg.hpp"
#include "abstraction/achievers_analysis.hpp"
#include "analysis/relaxed_planning_graph.hpp"
#include "analysis/numeric_relaxed_planning_graph.hpp"

#include "z3++.h"

// Helper function to write result and exit
int write_result_and_exit(const PlanGenerationResult& result, const char* output_file) {
    std::fstream output(output_file, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!output || !result.SerializeToOstream(&output)) {
        rantanplan::Logger::instance().error("Could not write result to file: " + std::string(output_file));
        return 1;
    }
    rantanplan::Logger::instance().info("Successfully wrote result to: " + std::string(output_file));
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}

// Function to export formula and exit
int export_formula_and_exit(const rantanplan::Problem& problem) {
    auto& config = rantanplan::Config::instance();

    // Validate formula export parameters
    if (config.formula_export.timestep < 0) {
        rantanplan::Logger::instance().error("--formula-timestep must be specified with --export-formula");
        return 1;
    }

    if (config.formula_export.output_file.empty()) {
        rantanplan::Logger::instance().error("--formula-output must be specified with --export-formula");
        return 1;
    }

    // Only allow formula export with strategies that support it
    auto strategy = rantanplan::StrategyRegistry::create(config.planner.strategy);
    if (!strategy->supports_formula_export()) {
        rantanplan::Logger::instance().error("Formula export is not supported by strategy '" + strategy->get_name() + "'");
        return 1;
    }

    try {
        // Create Z3 context
        z3::context ctx;

        // Create encoder, parallelism, and interference analyzer using strategy
        auto encoder = strategy->create_encoder(problem, ctx);
        auto parallelism = strategy->create_parallelism();
        auto interference = strategy->create_interference(problem);

        // Inject interference analyzer into parallelism strategy
        parallelism->set_interference_analyzer(std::move(interference));

        // Set parallelism strategy on encoder
        encoder->set_parallelism_strategy(std::move(parallelism));

        rantanplan::Logger::instance().info("Exporting formula for timestep " + std::to_string(config.formula_export.timestep)
                                       + " using strategy: " + encoder->get_parallelism_strategy_name());

        // Create formula exporter and generate formula
        rantanplan::FormulaExporter exporter(problem, *encoder, ctx);
        std::string formula = exporter.export_formula(config.formula_export.timestep);

        // Output formula to file
        std::ofstream output_file(config.formula_export.output_file);
        if (!output_file) {
            rantanplan::Logger::instance().error("Could not open output file: " + config.formula_export.output_file);
            return 1;
        }
        output_file << formula;
        rantanplan::Logger::instance().info("Formula exported to: " + config.formula_export.output_file);

        google::protobuf::ShutdownProtobufLibrary();
        return 0;

    } catch (const std::exception& e) {
        rantanplan::Logger::instance().error("Error during formula export: " + std::string(e.what()));
        google::protobuf::ShutdownProtobufLibrary();
        return 1;
    }
}

// Function to print the complete planning problem structure using enhanced planning classes
PlanGenerationResult solve_planning_problem(const rantanplan::Problem& problem) {
    auto& config = rantanplan::Config::instance();
    
    // Memory tracking is always enabled
    
    PlanGenerationResult result;
    auto* log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);

        // Create Z3 context
    z3::context ctx;

    // Create strategy
    auto strategy = rantanplan::StrategyRegistry::create(config.planner.strategy);

    rantanplan::Logger::instance().info("Using strategy: " + strategy->get_name());

    // Create encoder, parallelism, and interference analyzer using strategy
    auto encoder = strategy->create_encoder(problem, ctx);
    auto parallelism = strategy->create_parallelism();
    auto interference = strategy->create_interference(problem);

    // Inject interference analyzer into parallelism strategy
    parallelism->set_interference_analyzer(std::move(interference));

    // Set parallelism strategy on encoder
    encoder->set_parallelism_strategy(std::move(parallelism));

    // Create planner using strategy (strategy decides which planner to use!)
    auto planner = strategy->create_planner(problem, *encoder, ctx);

    // Get solver reference and create propagator using strategy
    auto propagator = strategy->create_propagator(planner->get_solver(), problem, *encoder);

    // Enable solver decision logging if requested
    if (config.has_log_file()) {
        propagator->enable_logging(config.logging.log_file, strategy->get_name());
    }

    planner->set_propagator_strategy(std::move(propagator));

    // Call planner->search() and get the result
    rantanplan::Plan plan = planner->search();
    if (planner->solution_found()) {
        // Plan found (even if empty) - populate the result
        result.set_status(PlanGenerationResult_Status_SOLVED_SATISFICING);
        
        // Convert plan to protobuf and set it in the result
        *result.mutable_plan() = plan.to_protobuf();
        
        if (config.is_info()) {
            log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("Plan found with " + std::to_string(plan.length()) + " actions.");
        }
    } else {
        // No plan found
        result.set_status(PlanGenerationResult_Status_UNSOLVABLE_INCOMPLETELY);
        if (config.is_info()) {
            log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("No plan found within the search limit.");
        }
    }
    
    if (config.is_verbose()) {
        log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("Finished solving the problem.");
    }
    
    // Add memory tracking information to result
    double current_memory = rantanplan::MemoryTracker::instance().get_current_memory_mb();
    
    log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);
    log_message->set_message("Memory usage - Current: " + std::to_string(current_memory) + " MB");

    return result;
}
int main(int argc, char* argv[]) {
    GOOGLE_PROTOBUF_VERIFY_VERSION;
    
    try {
        // Initialize configuration first
        rantanplan::Config::instance().initialize(argc, argv);
        auto& config = rantanplan::Config::instance();

        // Initialize logger with config
        rantanplan::Logger::instance().set_config(&config);

        if (argc < 3) {
            rantanplan::Logger::instance().error("Usage: " + std::string(argv[0]) + " <input_problem.pb> <output_solution.pb> [OPTIONS]");
            rantanplan::Logger::instance().error("Use --help for detailed options");
            return 1;
        }
    } catch (const std::exception& e) {
        rantanplan::Logger::instance().error("Configuration error: " + std::string(e.what()));
        return 1;
    }

    // Read the problem from the input file
    Problem problem_msg;
    std::fstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input || !problem_msg.ParseFromIstream(&input)) {
        rantanplan::Logger::instance().error("Could not open or parse problem file: " + std::string(argv[1]));
        return 1;
    }

    // Create a Problem wrapper from the protobuf message
    rantanplan::Problem planning_problem(problem_msg);
    //std::cout << planning_problem.to_string() << std::endl;

    // Check if formula export is requested
    auto& config = rantanplan::Config::instance();
    if (config.formula_export.export_formula) {
        return export_formula_and_exit(planning_problem);
    }

    // === GOAL REACHABILITY CHECK, ACTION REMOVAL, AND LOWER BOUND ===
    size_t total_actions = planning_problem.action_count();

    if (!config.global.enable_action_removal) {
        // Branch 1: No RPG - skip goal reachability check, no action removal, no lower bound
        config.planner.start_timestep = 0;

        rantanplan::Logger::instance().info("[Action Removal] Disabled - using all " + std::to_string(total_actions) + " actions");
        rantanplan::Logger::instance().info("[Lower Bound] Starting from timestep 0 (no RPG lower bound)");
    } else if (!config.global.use_numeric_rpg) {
        // Branch 2: Boolean RPG - check goal reachability, compute lower bound, remove actions
        rantanplan::RelaxedPlanningGraph rpg(planning_problem);
        bool goals_reachable = rpg.build();

        // If goals are not reachable in the relaxed planning graph, the problem is unsolvable
        if (!goals_reachable) {
            PlanGenerationResult result;
            result.set_status(PlanGenerationResult_Status_UNSOLVABLE_PROVEN);

            auto* log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("Problem proven unsolvable: goals not reachable in Boolean relaxed planning graph");

            return write_result_and_exit(result, argv[2]);
        }

        int rpg_lower_bound = rpg.get_minimum_steps_lower_bound();
        config.planner.start_timestep = rpg_lower_bound;

        auto removed_indices = rpg.get_removable_action_indices();
        size_t removed_actions = removed_indices.size();
        if (!removed_indices.empty()) {
            planning_problem = planning_problem.without_actions(removed_indices);
        }

        std::ostringstream lower_bound_msg, action_removal_msg;
        lower_bound_msg << "[Lower Bound] Boolean RPG lower bound: " << rpg_lower_bound << " steps";
        rantanplan::Logger::instance().info(lower_bound_msg.str());

        double percentage = (double)removed_actions / total_actions * 100.0;
        action_removal_msg << "[Action Removal] Removed " << removed_actions << "/" << total_actions
                          << " unreachable actions using Boolean RPG (" << std::fixed << std::setprecision(1)
                          << percentage << "%)";
        rantanplan::Logger::instance().info(action_removal_msg.str());
    } else {
        // Branch 3: Numeric RPG only
        z3::context ctx;

        rantanplan::NumericRelaxedPlanningGraph numeric_rpg(planning_problem, ctx);
        bool numeric_goals_reachable = numeric_rpg.build();

        // If goals are not reachable in the numeric relaxed planning graph, the problem is unsolvable
        if (!numeric_goals_reachable) {
            PlanGenerationResult result;
            result.set_status(PlanGenerationResult_Status_UNSOLVABLE_PROVEN);

            auto* log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("Problem proven unsolvable: goals not reachable in Numeric relaxed planning graph");

            return write_result_and_exit(result, argv[2]);
        }

        // Extract and set Numeric RPG lower bound
        int numeric_rpg_lower_bound = numeric_rpg.get_minimum_steps_lower_bound();
        config.planner.start_timestep = numeric_rpg_lower_bound;

        std::ostringstream numeric_lower_bound_msg;
        numeric_lower_bound_msg << "[Lower Bound] Numeric RPG lower bound: " << numeric_rpg_lower_bound << " steps";
        rantanplan::Logger::instance().info(numeric_lower_bound_msg.str());

        // Perform actual removal using Numeric RPG
        auto removed_indices = numeric_rpg.get_removable_action_indices();
        size_t removed_actions = removed_indices.size();
        if (!removed_indices.empty()) {
            planning_problem = planning_problem.without_actions(removed_indices);
        }

        std::ostringstream numeric_action_removal_msg;
        double percentage = (double)removed_actions / total_actions * 100.0;
        numeric_action_removal_msg << "[Action Removal] Removed " << removed_actions << "/" << total_actions
                                   << " unreachable actions using Numeric RPG (" << std::fixed << std::setprecision(1)
                                   << percentage << "%)";
        rantanplan::Logger::instance().info(numeric_action_removal_msg.str());
    }

    // Solve the planning problem using configuration
    PlanGenerationResult result = solve_planning_problem(planning_problem);

    // Print statistics if in debug mode, and optionally write to file
    if (config.is_debug()) {
        rantanplan::Stats::instance().print_all();
    }
    
    // Write statistics to file if specified
    if (!config.global.stats_file.empty()) {
        rantanplan::Stats::instance().write_to_file(config.global.stats_file);
    }

    return write_result_and_exit(result, argv[2]);
}