#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <iomanip>
#include <chrono>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include "unified_planning.pb.h" // Generated by protoc

#include "config/config.hpp"
#include "config/strategy_registry.hpp"
#include "config/strategy_factory.hpp"
#include "problem/problem.hpp"
#include "problem/protobuf_io.hpp"
#include "planners/sequential.hpp"
#include "planners/formula_exporter.hpp"
#include "util/memory_tracker.hpp"
#include "util/stats.hpp"
#include "util/logger.hpp"
#include "arpg/arpg.hpp"
#include "abstraction/achievers_analysis.hpp"
#include "passes/pipeline.hpp"
#include "passes/boolean_rpg_pass.hpp"
#include "passes/numeric_rpg_pass.hpp"
#include "passes/symmetry_pass.hpp"
#include "passes/grounding_pass.hpp"
#include "passes/cwa_initial_state_pass.hpp"

#include "z3++.h"

// Helper function to write result and exit
int write_result_and_exit(const PlanGenerationResult& result, const char* output_file) {
    std::fstream output(output_file, std::ios::out | std::ios::trunc | std::ios::binary);
    if (!output || !result.SerializeToOstream(&output)) {
        rantanplan::Logger::instance().error("Could not write result to file: " + std::string(output_file));
        return 1;
    }
    rantanplan::Logger::instance().info("Successfully wrote result to: " + std::string(output_file));
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}

// Function to export formula and exit
int export_formula_and_exit(const rantanplan::Problem& problem) {
    auto& config = rantanplan::Config::instance();

    // Validate formula export parameters
    if (config.formula_export.timestep < 0) {
        rantanplan::Logger::instance().error("--formula-timestep must be specified with --export-formula");
        return 1;
    }

    if (config.formula_export.output_file.empty()) {
        rantanplan::Logger::instance().error("--formula-output must be specified with --export-formula");
        return 1;
    }

    // Only allow formula export with strategies that support it
    const auto& spec = rantanplan::StrategyRegistry::get(config.planner.strategy);
    if (!rantanplan::supports_formula_export(spec)) {
        rantanplan::Logger::instance().error(
            "Formula export is not supported by strategy '" + config.planner.strategy + "'");
        return 1;
    }

    try {
        // Create Z3 context
        z3::context ctx;

        // Create encoder, parallelism, and interference analyzer using factory
        auto encoder = rantanplan::StrategyFactory::create_encoder(spec, problem, ctx);
        auto parallelism = rantanplan::StrategyFactory::create_parallelism(spec);
        auto interference = rantanplan::StrategyFactory::create_interference(spec, problem);

        // Inject interference analyzer into parallelism strategy
        parallelism->set_interference_analyzer(std::move(interference));

        // Set parallelism strategy on encoder
        encoder->set_parallelism_strategy(std::move(parallelism));

        rantanplan::Logger::instance().info("Exporting formula for timestep " + std::to_string(config.formula_export.timestep)
                                       + " using strategy: " + encoder->get_parallelism_strategy_name());

        // Create formula exporter and generate formula
        rantanplan::FormulaExporter exporter(problem, *encoder, ctx);
        std::string formula = exporter.export_formula(config.formula_export.timestep);

        // Output formula to file
        std::ofstream output_file(config.formula_export.output_file);
        if (!output_file) {
            rantanplan::Logger::instance().error("Could not open output file: " + config.formula_export.output_file);
            return 1;
        }
        output_file << formula;
        rantanplan::Logger::instance().info("Formula exported to: " + config.formula_export.output_file);

        google::protobuf::ShutdownProtobufLibrary();
        return 0;

    } catch (const std::exception& e) {
        rantanplan::Logger::instance().error("Error during formula export: " + std::string(e.what()));
        google::protobuf::ShutdownProtobufLibrary();
        return 1;
    }
}

PlanGenerationResult solve_planning_problem(const rantanplan::Problem& problem,
                                            const rantanplan::PipelineResult& pipeline_result) {
    auto& config = rantanplan::Config::instance();

    PlanGenerationResult result;
    auto* log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);

    z3::context ctx;

    const auto& spec = rantanplan::StrategyRegistry::get(config.planner.strategy);
    rantanplan::Logger::instance().info("Using strategy: " + config.planner.strategy);

    auto encoder = rantanplan::StrategyFactory::create_encoder(spec, problem, ctx);
    auto parallelism = rantanplan::StrategyFactory::create_parallelism(spec);
    auto interference = rantanplan::StrategyFactory::create_interference(spec, problem);

    parallelism->set_interference_analyzer(std::move(interference));
    encoder->set_parallelism_strategy(std::move(parallelism));

    // Set pipeline data on encoder
    encoder->set_symmetry_data(pipeline_result.symmetry_data);

    // Create planner using factory
    auto planner = rantanplan::StrategyFactory::create_planner(spec, problem, *encoder, ctx);

    // Get solver reference and create propagator using factory
    auto propagator = rantanplan::StrategyFactory::create_propagator(spec, planner->get_solver(), problem, *encoder);

    // Enable solver decision logging if requested
    if (config.has_log_file()) {
        propagator->enable_logging(config.logging.log_file, config.planner.strategy);
    }

    planner->set_propagator_strategy(std::move(propagator));

    // Call planner->search() and get the result
    rantanplan::Plan plan = planner->search();
    if (planner->solution_found()) {
        // Plan found (even if empty) - populate the result
        result.set_status(PlanGenerationResult_Status_SOLVED_SATISFICING);

        // Convert plan to protobuf and set it in the result
        *result.mutable_plan() = rantanplan::plan_to_protobuf(plan);

        if (config.is_info()) {
            log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("Plan found with " + std::to_string(plan.length()) + " actions.");
        }
    } else {
        // No plan found
        result.set_status(PlanGenerationResult_Status_UNSOLVABLE_INCOMPLETELY);
        if (config.is_info()) {
            log_message = result.add_log_messages();
            log_message->set_level(LogMessage_LogLevel_INFO);
            log_message->set_message("No plan found within the search limit.");
        }
    }

    if (config.is_verbose()) {
        log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("Finished solving the problem.");
    }

    // Add memory tracking information to result
    double current_memory = rantanplan::MemoryTracker::instance().get_current_memory_mb();

    log_message = result.add_log_messages();
    log_message->set_level(LogMessage_LogLevel_INFO);
    log_message->set_message("Memory usage - Current: " + std::to_string(current_memory) + " MB");

    return result;
}
int main(int argc, char* argv[]) {
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    try {
        // Initialize configuration first
        rantanplan::Config::instance().initialize(argc, argv);
        auto& config = rantanplan::Config::instance();

        // Initialize logger with config
        rantanplan::Logger::instance().set_config(&config);

        if (argc < 3) {
            rantanplan::Logger::instance().error("Usage: " + std::string(argv[0]) + " <input_problem.pb> <output_solution.pb> [OPTIONS]");
            rantanplan::Logger::instance().error("Use --help for detailed options");
            return 1;
        }
    } catch (const std::exception& e) {
        rantanplan::Logger::instance().error("Configuration error: " + std::string(e.what()));
        return 1;
    }

    // Read the problem from the input file
    Problem problem_msg;
    std::fstream input(argv[1], std::ios::in | std::ios::binary);
    if (!input || !problem_msg.ParseFromIstream(&input)) {
        rantanplan::Logger::instance().error("Could not open or parse problem file: " + std::string(argv[1]));
        return 1;
    }

    // Create a Problem wrapper from the protobuf message
    rantanplan::Problem planning_problem = rantanplan::load_problem_from_protobuf(problem_msg);
    //std::cout << planning_problem.to_string() << std::endl;

    // Check if formula export is requested
    auto& config = rantanplan::Config::instance();
    if (config.formula_export.export_formula) {
        return export_formula_and_exit(planning_problem);
    }

    // === PREPROCESSING PIPELINE ===
    rantanplan::BooleanRPGPass boolean_rpg_pass;
    rantanplan::NumericRPGPass numeric_rpg_pass;
    rantanplan::SymmetryDetectionPass symmetry_detection_pass;
    rantanplan::SymmetryCompletionPass symmetry_completion_pass;
    rantanplan::GroundingPass grounding_pass;
    rantanplan::CWAInitialStatePass cwa_pass;
    std::vector<const rantanplan::Pass*> passes;

    // Symmetry detection (SMT-based) runs BEFORE grounding — it only needs
    // initial state + goals and is the expensive part of symmetry analysis.
    if (config.symmetry.enable_symmetries) {
        passes.push_back(&symmetry_detection_pass);
    }

    if (config.global.reachability_grounding) {
        // C++ grounding performs reachability-based instantiation.
        // RPG seems redundant after C++ grounding
        // so it is disabled by default. Use --boolean-rpg or --numeric-rpg
        // to explicitly re-enable it.
        passes.push_back(&grounding_pass);
    }

    // CWA pass ensures all grounded fluents have explicit initial assignments.
    // Must run BEFORE any RPG pass so that NumericRPG's initialize_layer_0()
    // sees a fully-defined initial state (implicit-false booleans and
    // implicit-zero numerics are filled in here).
    // No-op when Python/UP already provides complete initial state.
    passes.push_back(&cwa_pass);

    if (config.global.reachability_grounding) {
        if (config.global.enable_action_removal) {
            passes.push_back(config.global.use_numeric_rpg
                             ? static_cast<const rantanplan::Pass*>(&numeric_rpg_pass)
                             : static_cast<const rantanplan::Pass*>(&boolean_rpg_pass));
        }
    } else if (config.global.enable_action_removal) {
        // When using UP grounding (--up-grounding), RPG is enabled by default
        // to prune unreachable actions from the cross-product grounding.
        passes.push_back(config.global.use_numeric_rpg
                         ? static_cast<const rantanplan::Pass*>(&numeric_rpg_pass)
                         : static_cast<const rantanplan::Pass*>(&boolean_rpg_pass));
    }

    // Symmetry completion runs AFTER grounding + CWA to compute variable
    // pairs (needs complete initial state) and action pairs (needs grounded actions).
    if (config.symmetry.enable_symmetries) {
        passes.push_back(&symmetry_completion_pass);
    }

    auto pipeline_result = rantanplan::run_pipeline(std::move(planning_problem), passes);
    planning_problem = std::move(pipeline_result.problem);
    config.planner.start_timestep = pipeline_result.lower_bound;

    // Record final action count after all pipeline passes (used for grounding analysis).
    rantanplan::Stats::instance().set("pipeline.final_actions",
                                      static_cast<double>(planning_problem.actions().size()));

    // Debug: dump problem info after pipeline
    if (config.is_debug()) {
        rantanplan::Logger::instance().info("After pipeline: " +
                    std::to_string(planning_problem.actions().size()) + " actions, " +
                    std::to_string(planning_problem.grounded_fluents().size()) + " grounded fluents, " +
                    std::to_string(planning_problem.initial_state().size()) + " initial assignments, " +
                    std::to_string(planning_problem.goals().size()) + " goals");
        // rantanplan::Logger::instance().info("Grounded fluents:");
        // for (const auto& gf : planning_problem.grounded_fluents()) {
        //     rantanplan::Logger::instance().info("  " + planning_problem.pool().to_string(gf));
        // }
    }

    if (pipeline_result.proven_unsolvable) {
        PlanGenerationResult result;
        result.set_status(PlanGenerationResult_Status_UNSOLVABLE_PROVEN);

        auto* log_message = result.add_log_messages();
        log_message->set_level(LogMessage_LogLevel_INFO);
        log_message->set_message("Problem proven unsolvable: goals not reachable in " + pipeline_result.unsolvable_reason);

        // Ensure stats are written even when exiting early due to unsolvability.
        if (!config.global.stats_file.empty()) {
            rantanplan::Stats::instance().write_to_file(config.global.stats_file);
        }

        return write_result_and_exit(result, argv[2]);
    }

    // Solve the planning problem using pipeline result
    PlanGenerationResult result = solve_planning_problem(planning_problem, pipeline_result);

    // Print statistics if in debug mode, and optionally write to file
    if (config.is_debug()) {
        rantanplan::Stats::instance().print_all();
    }

    // Write statistics to file if specified
    if (!config.global.stats_file.empty()) {
        rantanplan::Stats::instance().write_to_file(config.global.stats_file);
    }

    return write_result_and_exit(result, argv[2]);
}
