#include "sequential.h"
#include <fstream>

namespace planmt {

    SequentialPlanner::SequentialPlanner(const Problem& problem, GroundedEncoder&
    encoder, z3::context& ctx) : problem_(problem), encoder_(encoder), ctx_(ctx) {
    // Initialize planner with the given problem, encoder, and Z3 context
    }

    void SequentialPlanner::search() { 
        std::cout << "initial state:" << *encoder_.encode_initial_state() << std::endl;
        std::cout << "goal:" << *encoder_.encode_goal(1) << std::endl;
        std::cout << "actions:" << *encoder_.encode_actions(1) << std::endl;
        std::cout << "frames:" << *encoder_.encode_frames(1) << std::endl;
        std::cout << "parallelism:" << *encoder_.encode_parallelism(1) << std::endl;

        // Create Z3 solver to collect all constraints and output full SMT model
        z3::solver solver(ctx_);
        
        // Add all the constraints to the solver
        solver.add(*encoder_.encode_initial_state());
        solver.add(*encoder_.encode_goal(1));
        solver.add(*encoder_.encode_actions(1));
        solver.add(*encoder_.encode_frames(1));
        solver.add(*encoder_.encode_parallelism(1));
        
        // Output the complete SMT model to file for debugging
        std::ofstream smt_file("output.smt2");
        if (smt_file.is_open()) {
            // Output SMT-LIB header
            smt_file << ";; Automatically generated by planMT" << std::endl;
            smt_file << "(set-info :status unknown)" << std::endl;
            smt_file << std::endl;
            
            // Output individual assertions in their original form
            smt_file << ";; Initial State" << std::endl;
            smt_file << "(assert " << *encoder_.encode_initial_state() << ")" << std::endl;
            smt_file << std::endl;
            
            smt_file << ";; Goal" << std::endl;
            smt_file << "(assert " << *encoder_.encode_goal(1) << ")" << std::endl;
            smt_file << std::endl;
            
            smt_file << ";; Actions" << std::endl;
            smt_file << "(assert " << *encoder_.encode_actions(1) << ")" << std::endl;
            smt_file << std::endl;
            
            smt_file << ";; Frame Axioms" << std::endl;
            smt_file << "(assert " << *encoder_.encode_frames(1) << ")" << std::endl;
            smt_file << std::endl;
            
            smt_file << ";; Parallelism Constraints" << std::endl;
            smt_file << "(assert " << *encoder_.encode_parallelism(1) << ")" << std::endl;
            smt_file << std::endl;
            
            smt_file << ";; Check satisfiability" << std::endl;
            smt_file << "(check-sat)" << std::endl;
            smt_file << "(get-model)" << std::endl;
            
            smt_file.close();
            std::cout << "SMT model written to output.smt2" << std::endl;
        } else {
            std::cerr << "Error: Could not open output.smt2 for writing" << std::endl;
        }
    }

}
